// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	service "github.com/matt-hoiland/mocking/matching/service"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// MakeRequest provides a mock function with given fields: _a0
func (_m *Service) MakeRequest(_a0 *service.Request) *service.Response {
	ret := _m.Called(_a0)

	var r0 *service.Response
	if rf, ok := ret.Get(0).(func(*service.Request) *service.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Response)
		}
	}

	return r0
}
